apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: harbor.site-a.vcf.lab/library/busybox
    command: ["/bin/sh", "-c", "sleep 3600"]