apiVersion: crd.antrea.io/v1beta1
kind: ExternalIPPool
metadata:
  name: external-ip-pool-01
spec:
  ipRanges:
  - cidr: 192.168.16.40/29
  subnetInfo:
    prefixLength: 28
    vlan: 1001
    gateway:  192.168.16.33
  nodeSelector: {}
